### ISSUE TITLE
Error upon enabling Async Loading of AddThis resources

### ISSUE THREAD

**Issue by ctxlken** [collective/collective.addthis#9]
When attempting to check/enable the "Load AddThis resources asynchronously" checkbox option, I received this error:

AttributeError: 'NoneType' object has no attribute 'getEnabled'

So, async loading isn't yet working with v1.3.3 of collective.addthis.
